FROM evandrocoan/ubuntu18nodejspython:latest

# We can only set the backend IP and ports only before running `npm build` bellow
# https://github.com/facebook/create-react-app/issues/2353
ARG REACT_APP_GITHUB_RESEARCHER_BACKEND_IP
ARG REACT_APP_GITHUB_RESEARCHER_BACKEND_PORT

ENV REACT_APP_GITHUB_RESEARCHER_BACKEND_IP="${REACT_APP_GITHUB_RESEARCHER_BACKEND_IP}"
ENV REACT_APP_GITHUB_RESEARCHER_BACKEND_PORT="${REACT_APP_GITHUB_RESEARCHER_BACKEND_PORT}"

COPY . /app
WORKDIR /app/reactfrontend

RUN npm install
RUN npm install -g serve
RUN npm run build

WORKDIR /app
CMD ip a s && bash run_frontend.sh --production
