# Created a pre-built image for this project on:
# https://hub.docker.com/repository/docker/evandrocoan/ubuntu18nodejspython
#
# docker build . -f Dockerfile-nodejs -t evandrocoan/ubuntu18nodejspython
# docker run -it evandrocoan/ubuntu18nodejspython
# # nodejs --version
# # exit
# docker login docker.io
# docker push evandrocoan/ubuntu18nodejspython

FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y curl apt-utils
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs python3 python3-pip
RUN python3 -m pip install --upgrade pip

# https://github.com/vishnubob/wait-for-it
COPY ./wait-for-it.sh /bin/
RUN chmod +x /bin/wait-for-it.sh
RUN apt-get -y install iputils-ping dnsutils iproute2
