FROM githubrepositoryresearcher_reactfrontend

WORKDIR /app

RUN python3 -m pip install -r ./requirements.txt

# https://stackoverflow.com/questions/37461868/difference-between-run-and-cmd-in-a-dockerfile
# https://stackoverflow.com/questions/40454470/how-can-i-use-a-variable-inside-a-dockerfile-cmd
CMD ip a s && wait-for-it.sh pythonbackend:9000 -- wait-for-it.sh reactfrontend:3000 -- bash ./run_tests.sh
