FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y curl apt-utils
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs python3 python3-pip
RUN python3 -m pip install --upgrade pip

COPY ./wait-for-it.sh /bin/
RUN chmod +x /bin/wait-for-it.sh
RUN apt-get -y install iputils-ping dnsutils iproute2
