FROM evandrocoan/ubuntu18nodejspython:latest

# https://docs.docker.com/engine/reference/builder/
EXPOSE ${REACT_APP_GITHUB_RESEARCHER_FRONTEND_PORT}

COPY . /app
WORKDIR /app/reactfrontend

RUN npm install
RUN npm run build
RUN npm install -g serve

# https://stackoverflow.com/questions/37461868/difference-between-run-and-cmd-in-a-dockerfile
# https://stackoverflow.com/questions/40454470/how-can-i-use-a-variable-inside-a-dockerfile-cmd
CMD ip a s && serve -s build -l ${REACT_APP_GITHUB_RESEARCHER_FRONTEND_PORT}
