FROM evandrocoan/ubuntu18nodejspython:latest

# https://docs.docker.com/engine/reference/builder/
EXPOSE ${REACT_APP_GITHUB_RESEARCHER_BACKEND_PORT}

COPY . /app
WORKDIR /app

RUN python3 -m pip install -r ./requirements.txt

# https://stackoverflow.com/questions/37461868/difference-between-run-and-cmd-in-a-dockerfile
# https://stackoverflow.com/questions/40454470/how-can-i-use-a-variable-inside-a-dockerfile-cmd
CMD ip a s && bash run_backend.sh
