FROM githubrepositoryresearcher_reactfrontend

WORKDIR /app

RUN python3 -m pip install -r ./requirements.txt

CMD ip a s && wait-for-it.sh pythonbackend:9000 -- wait-for-it.sh reactfrontend:3000 -- bash ./run_tests.sh
